name: "Too many redirects"
author: "@jettplay"
category: "web"
description: |
  > Я тут изучал работу редиректов в новом веб-фреймворка, но кажется где-то ошибся. Можешь помочь найти проблему?
attribution: "Автор [@jettplay](https://t.me/jettplay)"
value: 1000
type: dynamic
extra:
    initial: 1000
    decay: 20
    minimum: 10
flags:
  - TyumenCTF{3rr_t00_m4ny_r3d1r3cts_F93CD9}
tags:
  - web
  - easy
connection_info: "http://5.1.53.43:5000/"
hints:
  - Обрати внимание на заголовки при редиректе.
state: visible
version: "0.1"
